version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: condoeconomy-postgres
    restart: always
    environment:
      POSTGRES_USER: condoadmin
      POSTGRES_PASSWORD: condopassword
      POSTGRES_DB: condoeconomy_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
