spring.application.name=condoeconomy-api

# Configurações do Banco de Dados PostgreSQL (Local via Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/condoeconomy_db
spring.datasource.username=condoadmin
spring.datasource.password=condopassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA e Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


