spring.application.name=condoeconomy-api

# Vamos usar o H2 em memória inicialmente para desenhar as tabelas rapidamente
# Quando a estrutura estiver madura, viramos a chave para o PostgreSQL.
spring.datasource.url=jdbc:h2:mem:condodb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar o console do H2 para debug
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
