CREATE TABLE usuario (
    id UUID PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    papel VARCHAR(50) NOT NULL -- ROLE_PORTEIRO, ROLE_SINDICO, ROLE_MORADOR
);
